### ISSUE TITLE
adjust tab switch animation speed and blur amount

### ISSUE THREAD

**Issue by zxsleebu** [JustAdumbPrsn/Nebula-A-Minimal-Theme-for-Zen-Browser#28]
i personally think that the tab animation is too visually heavy.
so i propose to make it lighter, more pleasant and snappy.

that's the settings that preserve the beauty of the animation and feel a lot lighter.

`Animations(tabs).css` file
```css
#tabbrowser-tabpanels > hbox:not(:has(.zen-glance-background)) {
  &:is([zen-split]) {
    transition: all 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.35), filter 0s ease-out !important;
  }
  &:not(.zen-glance-background):not([zen-split]) {
    transition: all 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.35), filter 0.18s ease-out !important;
    scale: 0.975 !important;
    opacity: 0;
    filter: blur(2px) !important;
  }
}
```
