### ISSUE TITLE
[Suggestion] Animation for active tab

### ISSUE THREAD

**Issue by allecsc** [JustAdumbPrsn/Nebula-A-Minimal-Theme-for-Zen-Browser#82]
Hi, it was hard for me to see the active tab I was currently on because everything is black in my setup so I've added the hovering animation to the active tab and I think it looks great. 

![Image](https://github.com/user-attachments/assets/d707f77a-004b-4aab-bbe3-d952b352bfd4)

I was wondering if you could add it as an option in about:config, for future releases.

```css
.tabbrowser-tab:hover::before,
.tabbrowser-tab[selected="true"]::before,
.tabbrowser-tab[visuallyselected="true"]::before {
  animation-play-state: running;
  opacity: 0.5;
}
```
